@echo off
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-1B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Llama-3.2-3B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id meta-llama/Meta-Llama-3.1-8B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-1.5B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-3B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-7B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 4
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 8
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version themed --prompt_k 5 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 0 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 1 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 3 --sample_size 50 --resolution 16
python structured_connections_solver.py --model_id Qwen/Qwen2.5-14B-Instruct --prompt_version default --prompt_k 5 --sample_size 50 --resolution 16